### ISSUE TITLE
Please update the documentation page

### ISSUE THREAD

**Issue by victorfern91** [feedzai/brushable-histogram#10]
I've forget this too in the last commit 😞 

So in my opinion I think that would be great add plugin like `husky` in order to automate the generation of the documentation tasks. What do you think about it @lfac-pt @nancruz @biamalveiro ?

I could do a PR in order to configure this

**Comment by nancruz** [comment]
@victorfern91 that would be very cool to have.

**Comment by victorfern91** [comment]
Very nice!
 I'll check a way to do that automatically or send feedback in the Pull Requests :smile:

**Comment by victorfern91** [comment]
This was addressed in #32
